name: Linting
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Vale
        uses: errata-ai/vale-action@v1.0.4
        with:
          config: https://raw.githubusercontent.com/department-of-veterans-affairs/vets-website/master/.vale.ini
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
