name: Linting
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Vale
        uses: errata-ai/vale-action@v1.0.4
        with:
          styles: |
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          config: https://github.com/department-of-veterans-affairs/vets-website/blob/55889c9ccac176951e8e9bfa78e15bcb6188c5fc/.vale.ini
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
